'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34014
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("BatMath.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1_render__63_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_1_render__63_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _14() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_14", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1837_batman_ac_bruce_wayne_prev() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_1837_batman_ac_bruce_wayne_prev", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1841_batman_ac_gargoyle_prev() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_1841_batman_ac_gargoyle_prev", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1907591_screenshot017x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_1907591_screenshot017x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _208a1wj() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_208a1wj", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _2758_batman_arkham_city_prev() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_2758_batman_arkham_city_prev", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _2779_render_Joker() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_2779_render_Joker", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _2cg1pck() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_2cg1pck", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _5557_render_01825420_photo_batman_arkham_asylum() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_5557_render_01825420_photo_batman_arkham_asylum", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _664AA87C0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_664AA87C0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _6841_render_joker_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_6841_render_joker_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _6841_render_joker_12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_6841_render_joker_12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _9335_render_BatmanAnime1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_9335_render_BatmanAnime1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _9415_render_render_joker() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_9415_render_render_joker", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ajax_loader() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ajax_loader", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property atman() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("atman", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ba_tman() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ba_tman", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Baman() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Baman", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property batm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("batm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BatMa() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BatMa", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property batman() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("batman", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Batman_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Batman_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Batman_202() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Batman_202", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property batman_2608() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("batman_2608", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Batman_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Batman_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Batman_34() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Batman_34", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Batman_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Batman_4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Batman_Animated_02_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Batman_Animated_02_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Batman_Arkham_Asylum_Render_psd34809() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Batman_Arkham_Asylum_Render_psd34809", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property batman_arkham_asylum_sigtutorials() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("batman_arkham_asylum_sigtutorials", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Batman_fireproof() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Batman_fireproof", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property batman_render() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("batman_render", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property batman_render_005_by_seadaemon_d5imuoo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("batman_render_005_by_seadaemon_d5imuoo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Batman_render_01_lo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Batman_render_01_lo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Batman_Render1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Batman_Render1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Batman_Vengance() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Batman_Vengance", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BatmanArkhamAsylum() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BatmanArkhamAsylum", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BatmanLoad() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BatmanLoad", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BatmanRender() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BatmanRender", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property batmanrenderneod_cop2y() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("batmanrenderneod_cop2y", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BatmanToon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BatmanToon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Batmn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Batmn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property botmon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("botmon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Copia_de_1_render__63_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Copia_de_1_render__63_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Copia_de_2cg1pck() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Copia_de_2cg1pck", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Copia_de_5557_render_01825420_photo_batman_arkham_asylum() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Copia_de_5557_render_01825420_photo_batman_arkham_asylum", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Copia_de_6841_render_joker_12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Copia_de_6841_render_joker_12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Copia_de_9335_render_BatmanAnime1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Copia_de_9335_render_BatmanAnime1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Copia_de_batm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Copia_de_batm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Copia_de_BatMa() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Copia_de_BatMa", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property eraabylego() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("eraabylego", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property joker() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("joker", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property joker_cut_out() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("joker_cut_out", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Joker_Cutout() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Joker_Cutout", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property joker_render__render_warcraft__the_joker_render__world_of_warcraft_render() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("joker_render__render_warcraft__the_joker_render__world_of_warcraft_render", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property joker2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("joker2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property joker21qg1gq() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("joker21qg1gq", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Loading() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Loading", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mkvsdc_batman() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mkvsdc_batman", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property normal_batman_1910() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("normal_batman_1910", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property normal_batman_28329() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("normal_batman_28329", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property normal_Batman1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("normal_Batman1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pb_sq_40690_lg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pb_sq_40690_lg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property render_batman_3_by_kypexfly_d5806tv() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("render_batman_3_by_kypexfly_d5806tv", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property render_batman_exclusivo_panico_renders() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("render_batman_exclusivo_panico_renders", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property render_batman4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("render_batman4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property the_dark_knight_batman() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("the_dark_knight_batman", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property void_0_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("void_0_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
